name: Terraform CI/CD    

on:
  push:
    branches:
      - main

jobs:
  terraform:   
    name: 'Terraform Lint, Security Check, and Deploy'
    runs-on: self-hosted  # Use 'ubuntu-latest' if using GitHub-hosted runner

    env:
      AWS_REGION: 'ap-south-1'
      TF_VERSION: '1.4.0'   
      TFLINT_VERSION: '0.46.1'  
      TFSEC_VERSION_
