name: Terraform CI/CD    

on:
  push:
    branches:
      - main

jobs:
  terraform:   
    name: 'Terraform Init, Format, Validate, Plan, Apply'
    runs-on: ubuntu-latest  # You can change this to 'self-hosted' if you use a self-hosted runner

    env:
      AWS_REGION: 'ap-south-1'
      TF_VERSION: '1.4.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -chdir=./test/S3

      - name: Terraform Format Check
        run: terraform fmt -check -chdir=./test/S3

      - name: Terraform Validate
        run: terraform validate -chdir=./test/S3

      - name: Terraform Plan
        run: terraform plan -out=tfplan -chdir=./test/S3

      - name: Show Terraform Plan
        run: terraform show tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Apply only on the main branch
        run: terraform apply -auto-approve -chdir=./test/S3
